### ISSUE TITLE
Implement ball

### ISSUE THREAD

**Issue by Zereijin** [Zereijin/GMTK2023#2]
Ball should slide down the table by default.
Ball should bounce off walls

For now, let's just implement the following controls:
Bump
- [x] Impart a little bit of impact left or right when button is pressed

Slow down
- [x] Hold a configurable button to reduce vertical speed
- [x] Stop slow down if button is released early
- [x] Have a tuneable maximum hold down time

Appearance
- [x] Use a texture

**Comment by Hawk777** [comment]
Fixed in 3ce73b1343b4f5a5986f5d134112677c5fe42a94
