### ISSUE TITLE
Monodirectional bumper

### ISSUE THREAD

**Issue by Zereijin** [Zereijin/GMTK2023#25]
Bumper should only bump in one direction
If crossing the other direction, pass through the bumper

If possible, make sure the ball is approaching the bumpable side from entirely outside the bumper before bumping it; if it passes part way through the passable side, it shouldn't get bumped

**Comment by doublea999** [comment]
Implemented in c705da24fddf7a3747e55ffe9f54f90e27b5c95b with the [one-way-collision](https://docs.godotengine.org/en/stable/classes/class_collisionshape2d.html#class-collisionshape2d-property-one-way-collision) property in CollisionShape2D. Looks like it works exactly the way we desire.
