### ISSUE TITLE
Implement flipper

### ISSUE THREAD

**Issue by Zereijin** [Zereijin/GMTK2023#3]
Flippers should be placeable, sizeable, and flippable by design
Flippers wait for the ball to enter a zone before automatically flipping to hit the ball
- this should be slightly sub-perfect so that the player can try to outsmart the flipper into sub-optimal hits
When hitting the ball, flippers should impart a force on the ball as physically expected

**Comment by Hawk777** [comment]
Fixed in 7a53218fbe6047b69049e7ef70ae2ed3654f1bce
