### ISSUE TITLE
Lowscore

### ISSUE THREAD

**Issue by Zereijin** [Zereijin/GMTK2023#33]
Keep a record of the player's lowest scores.
Lowscores should be persistent. If it's stored locally, it's fine if the player can delete them.

As the stretchest of stretch goals, we can try to have a competitive lowscore board, where people can attach their names to their scores and have them publically viewable.

**Comment by Hawk777** [comment]
Fixed in 869ed70a19118042aabb14d41d7648baf5520e77.
