### ISSUE TITLE
Fix character "I" in Keytpunch029 font

### ISSUE THREAD

**Issue by doublea999** [Zereijin/GMTK2023#34]
`I` and 'i' in this fixed-width font are aligned to the left, rather than centered. :'(

The font package does provide source `sfd` files and a Python script to generate the `otf` font files
  - Note: The Python script is written for Python 2

One possible quick fix: Set the width narrower and regenerating the font:
  - Under `StartChar: I` and `StartChar: i` in the source file `src/Keypunch029 Regular.sfd`:
    - lower the `Width` value

https://fontlibrary.org/en/font/keypunch029

**Comment by doublea999** [comment]
I can look into this when there is no other higher priority tasks.

**Comment by amimoto** [comment]
Updated `Keypunch029.otf` with FontForge. The letter `i` and `I` works so marking this ticket closed.
