### ISSUE TITLE
Bumper graphics

### ISSUE THREAD

**Issue by doublea999** [Zereijin/GMTK2023#35]
Need graphics for
- the active "bouncy" part of the bumper
  - when idle
  - when bumping: can be single image, or multiple frames
- the inactive (triangle) enclosure

I believe these bumpers are going to be used as one-way gates as well. So perhaps the bouncy graphics is attached to the bumper object and is common to both types, while the triangle bumper "enclosure" would be separate graphics that is manually put onto the game scene. Just my guess. Should check in with @Zereijin regarding intentions.

**Comment by doublea999** [comment]
Files can be added to the `bumper` directory, and @doublea999 will attach them to the bumper object. :pray:

**Comment by Fyda** [comment]
pushed 3 images:
- bumper.png (resting state)
- bumper_lit.png (when hit)
- bumper_bouncer.png (to be layered underneath the above images, with the origin/anchor point set to the bottom-left if possible, and then animated to scale up just enough to peek out)
