### ISSUE TITLE
Style the end-of-game screen

### ISSUE THREAD

**Issue by Hawk777** [Zereijin/GMTK2023#39]
It exists, but it looks horrific. Make it look not horrific.

**Comment by Fyda** [comment]
I have added style (but function is still needed)

**Comment by Hawk777** [comment]
I guess this goes over to @Zereijin then? I’m unclear on what additional functionality is needed; I thought all we wanted was to show the low-score list and permit continuing to the main menu.

**Comment by Hawk777** [comment]
I think this is done now. Buttons work and there is a dimming layer behind it.
