### ISSUE TITLE
Fill out metadata on itch.io

### ISSUE THREAD

**Issue by Hawk777** [Zereijin/GMTK2023#42]

**Comment by doublea999** [comment]
At https://itch.io/game/release-info/2155613:
"License for Code" has no option for CC-NC-SA, or any CC at all

**Comment by doublea999** [comment]
Missing items:
- Game tagline
- Game description
- Cover image
- Code license
- Favicon
- Logo
- Screenshots

**Comment by Fyda** [comment]
filled in all but the code license
