### ISSUE TITLE
Pathetic partyblower sound

### ISSUE THREAD

**Issue by Zereijin** [Zereijin/GMTK2023#51]
Play when spitting confetti
Modulate sound

**Comment by Zereijin** [comment]
Example: https://www.youtube.com/watch?v=Nzup8Nl0qdU

**Comment by Fyda** [comment]
pushed /game_scene/confetti/partyblower.ogg

**Comment by Hawk777** [comment]
Fixed in 7c7a95a3637b323d5f2efec6bbf551c170472a1f
