### ISSUE TITLE
Score pylon graphic

### ISSUE THREAD

**Issue by Zereijin** [Zereijin/GMTK2023#8]
Need a generic thing to hit for points
![image](https://github.com/Zereijin/GMTK2023/assets/25259186/4a2519d0-cc79-4bd2-9238-cf711bc0d9b3)
Should be able to animate somewhat to indicate it has been struck

**Comment by Fyda** [comment]
I've pushed:
- pylon.png (central star cutout is unlit)
- pylon_hit.png (central star cutout is lit)
