### ISSUE TITLE
Get fonts

### ISSUE THREAD

**Issue by Zereijin** [Zereijin/GMTK2023#9]
A general font for most UI
A retro number font for the scoreboard

**Comment by doublea999** [comment]
- https://fontlibrary.org/en/font/keypunch029
- https://fontlibrary.org/en/font/threefourtwotwo

Both under [OFL (SIL Open Font License)](http://scripts.sil.org/OFL)

**Comment by doublea999** [comment]
Text doesn't align vertically nicely in buttons.

See #21
